### PR TITLE
fix None issue

### PR DESCRIPTION
**Pull request by jxchen01**
Currently, the validator may try to cast a NoneType object to others or cast others to None. This PR attempts to fix this issue.

### CODE REVIEW

**Comment by jxchen01** [comment]
@toloudis , who else should I request for review?

**Review by GabeMedrash — APPROVED** [review]
lgtm!

**Review by vianamp — APPROVED** [review]

**Review by toloudis — APPROVED** [review]
I'm not sure who are the maintainers of this repo!  But these changes look fine.

**Comment by toloudis** [comment]
@evamaxfield has done most if not all of the prior commits, might want to take a look

**Review by evamaxfield — APPROVED** [review]
Looks good to me!

**Pull request merged**
